---
name: Generate registry.yaml
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/generate-registry.yaml
      - aqua/generate-registry.yaml
      - registry.yaml
      - pkgs/**/registry.yaml
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/generate-registry.yaml
      - aqua/generate-registry.yaml
      - registry.yaml
      - pkgs/**/registry.yaml
jobs:
  generate-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.21.3
      - uses: aquaproj/registry-action/generate-registry@v0.2.0
