---
name: prettier
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i -g prettier
      - run: prettier -c .
