name: renovate-config-validator

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json
  push:
    branches:
      - master
      - renovate/**
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@ca480cb7ec89a9e1cd8c214ad33bda1617184027 # v2.0.0
