name: renovate-config-validator

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json
  push:
    branches:
      - master
      - renovate/**
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@1e1604219a6b38ae9a10aff42a28a3656322c31a # v2.4.1
