---
name: test
on:
  push:
    branches:
      - renovate/**
    paths:
      - 'aqua-config/**'
      - '.github/workflows/*.yaml'
      - 'package*.json'
  pull_request:
    branches: [master]
    paths:
      - 'aqua-config/**'
      - '.github/workflows/*.yaml'
      - 'package*.json'
env:
  AQUA_LOG_COLOR: always
  GITHUB_TOKEN: ${{ github.token }}
  CI_INFO_TEMP_DIR: /tmp/ci-info
jobs:
  ci-info:
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: aqua/ci-info.yaml
    steps:
      - run: mkdir "$CI_INFO_TEMP_DIR"
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.32.0
      - uses: suzuki-shunsuke/ci-info-action/store@ceeb10dd50cd632db31e7eccf92cbbb6856f3191 # v0.1.3
      - run: echo "https://github.com/aquaproj/aqua-registry/pull/$CI_INFO_PR_NUMBER" >> "$GITHUB_STEP_SUMMARY"

  test:
    needs: ci-info
    strategy:
      matrix:
        env:
          - runs-on: windows-latest
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
          - runs-on: ubuntu-latest
            goarch: arm64
          # - runs-on: ubuntu-latest
          #   goos: darwin
          #   goarch: arm64
          # - runs-on: windows-latest
          #   goarch: arm64
    runs-on: ${{ matrix.env.runs-on }}
    defaults:
      run:
        shell: bash
    env:
      AQUA_CONFIG: aqua-config/all.yaml
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: suzuki-shunsuke/ci-info-action/restore@ceeb10dd50cd632db31e7eccf92cbbb6856f3191 # v0.1.3

      # - name: Generate token
      #   id: generate_token
      #   uses: tibdex/github-app-token@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.32.0

      # - uses: aquaproj/registry-action/test@v0.2.0
      #   with:
      #     goarch: ${{ matrix.env.goarch }}
      #     go_version: "1.18.5"
      #   # env:
      #   #   GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

  # This job is used for branch protection rule
  # Add this job to `Status checks that are required`
  status-check:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - run: exit 1
